In [1]:
import pandas as pd
from surprise import SVD, Reader

In [2]:
from surprise import Dataset


In [3]:
from surprise.model_selection import cross_validate

In [4]:
data = Dataset.load_builtin('ml-100k')
print("done")

done


In [5]:
data

In [6]:
algo = SVD()

In [7]:
cross_validate(algo, data, measures=['RMSE','MAE'], cv = 5, verbose=True)

Evaluating RMSE, MAE of algorithm SVD on 5 split(s).

                  Fold 1  Fold 2  Fold 3  Fold 4  Fold 5  Mean    Std     
RMSE (testset)    0.9384  0.9322  0.9383  0.9329  0.9391  0.9362  0.0030  
MAE (testset)     0.7360  0.7330  0.7396  0.7374  0.7412  0.7374  0.0028  
Fit time          0.71    0.74    0.70    0.71    0.70    0.71    0.01    
Test time         0.12    0.11    0.08    0.11    0.11    0.11    0.02    


{'test_rmse': array([0.93836569, 0.93216458, 0.93834638, 0.93292883, 0.93906784]),
 'test_mae': array([0.73596845, 0.73301084, 0.73955738, 0.73744646, 0.74122329]),
 'fit_time': (0.7097668647766113,
  0.7379388809204102,
  0.704719066619873,
  0.7144584655761719,
  0.7027840614318848),
 'test_time': (0.12330293655395508,
  0.11238956451416016,
  0.07526659965515137,
  0.10710000991821289,
  0.11238765716552734)}

In [8]:
df = pd.read_csv("pauwel-dataset.txt", sep='\t', header=0)

In [9]:
df

abdominal cramps  abdominal distention  \
carnitine                                 1                     0   
GABA                                      0                     0   
delta-aminolevulinic acid                 0                     0   
leucovorin                                0                     0   
PGE2                                      0                     0   
...                                     ...                   ...   
pimecrolimus                              0                     0   
auranofin                                 0                     0   
cefditoren                                0                     0   
nitroprusside                             0                     0   
gold sodium thiomalate                    0                     0   

                           abdominal pain  malformations  \
carnitine                               0              0   
GABA                                    0              0   
delta-aminolevulinic acid               0              0   
leucovorin                              0              0   
PGE2                                    1              0   
...                                   ...            ...   
pimecrolimus                            1              0   
auranofin                               1              0   
cefditoren                              1              0   
nitroprusside                           1              0   
gold sodium thiomalate                  0              0   

                           spontaneous abortion  missed abortion  abscess  \
carnitine                                     0                0        0   
GABA                                          0                0        0   
delta-aminolevulinic acid                     0                0        0   
leucovorin                                    0                0        0   
PGE2                                          0                0        0   
...                                         ...              ...      ...   
pimecrolimus                                  0                0        0   
auranofin                                     0                0        0   
cefditoren                                    0                0        0   
nitroprusside                                 0                0        0   
gold sodium thiomalate                        0                0        0   

                           acanthosis nigricans  acidosis  \
carnitine                                     0         0   
GABA                                          0         0   
delta-aminolevulinic acid                     0         0   
leucovorin                                    0         0   
PGE2                                          0         1   
...                                         ...       ...   
pimecrolimus                                  0         0   
auranofin                                     0         0   
cefditoren                                    0         0   
nitroprusside                                 0         0   
gold sodium thiomalate                        0         0   

                           renal tubular acidosis  ...  drug dependence  \
carnitine                                       0  ...                1   
GABA                                            0  ...                0   
delta-aminolevulinic acid                       0  ...                0   
leucovorin                                      0  ...                0   
PGE2                                            0  ...                0   
...                                           ...  ...              ...   
pimecrolimus                                    0  ...                0   
auranofin                                       0  ...                0   
cefditoren                                      0  ...                0   
nitroprusside                                   0  ...               

In [10]:
drug_names = df.index.to_numpy()
len(drug_names)




888

In [11]:
drug_names[0]

'carnitine'

In [12]:
se_names = df.columns.to_numpy()
len(se_names)

1385

In [13]:
se_names[0]

'abdominal cramps'

In [14]:
# creating a list of tuples in the form (drug, side effect, presence)

drug_se = []
count = 0
# for drug in drug_names
for drug in drug_names:
    for side_fx in se_names:
        drug_se.append((drug, side_fx, df.loc[drug, side_fx]))
        count = count+1

print(count)

1229880


In [15]:
len(drug_se)
count

1229880

In [16]:
# make it into a dataframe

df_new = pd.DataFrame.from_records(drug_se, columns=['drug', 'side effect', 'presence/absence'])

In [17]:
df_new


drug              side effect  presence/absence
0                     carnitine         abdominal cramps                 1
1                     carnitine     abdominal distention                 0
2                     carnitine           abdominal pain                 0
3                     carnitine            malformations                 0
4                     carnitine     spontaneous abortion                 0
...                         ...                      ...               ...
1229875  gold sodium thiomalate   eosinophilic pneumonia                 0
1229876  gold sodium thiomalate  retinal vein thrombosis                 0
1229877  gold sodium thiomalate      renal insufficiency                 0
1229878  gold sodium thiomalate  glioblastoma multiforme                 0
1229879  gold sodium thiomalate         portal cirrhosis                 0

[1229880 rows x 3 columns]

In [18]:
reader = Reader(rating_scale= (0,1))
data = Dataset.load_from_df(df_new, reader)

In [19]:
cross_validate(algo, data, measures=['RMSE','MAE'], cv = 5, verbose=True)

Evaluating RMSE, MAE of algorithm SVD on 5 split(s).

                  Fold 1  Fold 2  Fold 3  Fold 4  Fold 5  Mean    Std     
RMSE (testset)    0.1756  0.1730  0.1729  0.1744  0.1749  0.1741  0.0011  
MAE (testset)     0.0668  0.0662  0.0659  0.0665  0.0668  0.0664  0.0004  
Fit time          8.68    9.18    9.20    9.17    9.22    9.09    0.21    
Test time         1.93    1.93    1.66    1.86    1.93    1.86    0.10    


{'test_rmse': array([0.17557077, 0.17302737, 0.17286874, 0.17436418, 0.17490861]),
 'test_mae': array([0.06680071, 0.06624979, 0.06586072, 0.06647043, 0.06683698]),
 'fit_time': (8.675248622894287,
  9.183786630630493,
  9.200395822525024,
  9.167433738708496,
  9.220792531967163),
 'test_time': (1.9251751899719238,
  1.927488088607788,
  1.6612677574157715,
  1.8583457469940186,
  1.9262030124664307)}

In [20]:
mizutani_df = pd.read_csv("mizutani-dataset.txt", sep='\t', header=0)

In [21]:
mizutani_df



abdominal.cramps  abdominal.distention  abdominal.pain  \
85                       1                     0               0   
119                      0                     0               0   
137                      0                     0               0   
143                      0                     0               0   
158                      0                     0               1   
...                    ...                   ...             ...   
6398525                  0                     0               0   
6398970                  0                     0               1   
6447131                  0                     0               1   
6918453                  0                     0               1   
11947681                 0                     0               1   

          malformations  spontaneous.abortion  missed.abortion  abscess  \
85                    0                     0                0        0   
119                   0                     0                0        0   
137                   0                     0                0        0   
143                   0                     0                0        0   
158                   0                     0                0        0   
...                 ...                   ...              ...      ...   
6398525               0                     0                0        0   
6398970               0                     0                0        0   
6447131               0                     0                0        0   
6918453               0                     0                0        0   
11947681              0                     0                0        0   

          acanthosis.nigricans  acidosis  renal.tubular.acidosis  ...  \
85                           0         0                       0  ...   
119                          0         0                       0  ...   
137                          0         0                       0  ...   
143                          0         0                       0  ...   
158                          0         1                       0  ...   
...                        ...       ...                     ...  ...   
6398525                      0         0                       0  ...   
6398970                      0         0                       0  ...   
6447131                      0         0                       0  ...   
6918453                      0         0                       0  ...   
11947681                     0         0                       0  ...   

          vitamin.deficiency  drug.dependence  diverticulosis  \
85                         0                1               0   
119                        0                0               0   
137                        0                0               0   
143                        0                0               0   
158                        0                0               0   
...                      ...              ...             ...   
6398525                    0                0               0   
6398970                    0                0               0   
6447131                    0                0               0   
6918453                    0                0               0   
11947681                   0                0               0   

          prostatic.hypertrophy  allergic.reaction  dysphonia  \
85                            0                  1          0   
119                           0                  0          0   
137                           0                  0          0   
143                           0                  0          0   
158                           0                  0          0   
...                         ...                ...        ...   
6398525                       0                  0          0   
6398970                       0                  1          0   
6447131                       0                  

In [27]:
drug_codes = mizutani_df.index.to_numpy()

drug_codes

array([      85,      119,      137,      143,      158,      159,
            175,      191,      214,      232,      247,      271,
            298,      444,      450,      564,      596,      598,
            681,      738,      750,      772,      838,      861,
            888,      937,      942,      951,     1003,     1046,
           1065,     1071,     1125,     1148,     1206,     1302,
           1546,     1690,     1775,     1935,     1978,     1986,
           2022,     2083,     2088,     2092,     2118,     2130,
           2131,     2133,     2141,     2145,     2153,     2156,
           2160,     2162,     2170,     2179,     2182,     2215,
           2216,     2232,     2244,     2249,     2250,     2265,
           2266,     2267,     2283,     2284,     2308,     2311,
           2315,     2344,     2366,     2369,     2370,     2375,
           2381,     2405,     2431,     2435,     2441,     2443,
           2462,     2471,     2474,     2476,     2477,     2

In [30]:
se_names_mizutani = mizutani_df.columns.to_numpy()
se_names_mizutani

array(['abdominal.cramps', 'abdominal.distention', 'abdominal.pain', ...,
       'retinal.vein.thrombosis', 'renal.insufficiency',
       'glioblastoma.multiforme'], dtype=object)

In [1]:
import numpy as np
import tensorflow as tf
from tensorflow import keras
import pandas as pd
import seaborn as sns
from pylab import rcParams
import string
import re
import matplotlib.pyplot as plt
import math
from matplotlib import rc
# from google.colab import drive
from sklearn.model_selection import train_test_split
from collections import Counter, defaultdict
from sklearn.metrics import accuracy_score
import matplotlib.ticker as ticker
from math import sqrt

from sklearn.metrics import mean_squared_error

%matplotlib inline

sns.set(style='whitegrid', palette='muted', font_scale=1.3)

rcParams['figure.figsize'] = 14, 8

RANDOM_SEED = 42

np.random.seed(RANDOM_SEED)

2023-01-17 00:07:00.483704: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2023-01-17 00:07:02.635512: W tensorflow/compiler/xla/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libnvinfer.so.7'; dlerror: libnvinfer.so.7: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: :/home/andrea/miniconda3/envs/tf/lib/
2023-01-17 00:07:02.638814: W tensorflow/compiler/xla/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libnvinfer_plugin.so.7'; dlerror: libnvinfer_plugin.so.7: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: :/home/andrea/miniconda3/envs/tf/lib/
2023-01-17 00:07:02.638838: W tensorflow/compiler/tf2t

In [2]:
# creating a list of tuples in the form (drug, side effect, presence)

drug_se_mizutani = []
count = 0
# for drug in drug_names
for drug in drug_codes:
    for side_fx in se_names_mizutani:
        value = mizutani_df.loc[drug, side_fx]
        drug_se_mizutani.append((drug, side_fx, value))
        if value == 1:
            count = count+1

print(count)

NameError: name 'drug_codes' is not defined

In [37]:
df_mizutani_new = pd.DataFrame.from_records(drug_se_mizutani, columns=['drug', 'side effect', 'presence/absence'])
df_mizutani_new

drug              side effect  presence/absence
0             85         abdominal.cramps                 1
1             85     abdominal.distention                 0
2             85           abdominal.pain                 0
3             85            malformations                 0
4             85     spontaneous.abortion                 0
...          ...                      ...               ...
881057  11947681                dysphonia                 0
881058  11947681   eosinophilic.pneumonia                 0
881059  11947681  retinal.vein.thrombosis                 0
881060  11947681      renal.insufficiency                 0
881061  11947681  glioblastoma.multiforme                 0

[881062 rows x 3 columns]

# Start

In [2]:
# Starting again
# Load the datasets
# Pauwel

pauwel = pd.read_csv("pauwel-dataset.txt", sep='\t', header=0)

In [3]:
pauwel

abdominal cramps  abdominal distention  \
carnitine                                 1                     0   
GABA                                      0                     0   
delta-aminolevulinic acid                 0                     0   
leucovorin                                0                     0   
PGE2                                      0                     0   
...                                     ...                   ...   
pimecrolimus                              0                     0   
auranofin                                 0                     0   
cefditoren                                0                     0   
nitroprusside                             0                     0   
gold sodium thiomalate                    0                     0   

                           abdominal pain  malformations  \
carnitine                               0              0   
GABA                                    0              0   
delta-aminolevulinic acid               0              0   
leucovorin                              0              0   
PGE2                                    1              0   
...                                   ...            ...   
pimecrolimus                            1              0   
auranofin                               1              0   
cefditoren                              1              0   
nitroprusside                           1              0   
gold sodium thiomalate                  0              0   

                           spontaneous abortion  missed abortion  abscess  \
carnitine                                     0                0        0   
GABA                                          0                0        0   
delta-aminolevulinic acid                     0                0        0   
leucovorin                                    0                0        0   
PGE2                                          0                0        0   
...                                         ...              ...      ...   
pimecrolimus                                  0                0        0   
auranofin                                     0                0        0   
cefditoren                                    0                0        0   
nitroprusside                                 0                0        0   
gold sodium thiomalate                        0                0        0   

                           acanthosis nigricans  acidosis  \
carnitine                                     0         0   
GABA                                          0         0   
delta-aminolevulinic acid                     0         0   
leucovorin                                    0         0   
PGE2                                          0         1   
...                                         ...       ...   
pimecrolimus                                  0         0   
auranofin                                     0         0   
cefditoren                                    0         0   
nitroprusside                                 0         0   
gold sodium thiomalate                        0         0   

                           renal tubular acidosis  ...  drug dependence  \
carnitine                                       0  ...                1   
GABA                                            0  ...                0   
delta-aminolevulinic acid                       0  ...                0   
leucovorin                                      0  ...                0   
PGE2                                            0  ...                0   
...                                           ...  ...              ...   
pimecrolimus                                    0  ...                0   
auranofin                                       0  ...                0   
cefditoren                                      0  ...                0   
nitroprusside                                   0  ...               

In [4]:
# mizutani dataset
mizutani = pd.read_csv("mizutani-dataset.txt", sep='\t', header=0)

In [5]:
# the drug names are coded with pubchem id
mizutani

abdominal.cramps  abdominal.distention  abdominal.pain  \
85                       1                     0               0   
119                      0                     0               0   
137                      0                     0               0   
143                      0                     0               0   
158                      0                     0               1   
...                    ...                   ...             ...   
6398525                  0                     0               0   
6398970                  0                     0               1   
6447131                  0                     0               1   
6918453                  0                     0               1   
11947681                 0                     0               1   

          malformations  spontaneous.abortion  missed.abortion  abscess  \
85                    0                     0                0        0   
119                   0                     0                0        0   
137                   0                     0                0        0   
143                   0                     0                0        0   
158                   0                     0                0        0   
...                 ...                   ...              ...      ...   
6398525               0                     0                0        0   
6398970               0                     0                0        0   
6447131               0                     0                0        0   
6918453               0                     0                0        0   
11947681              0                     0                0        0   

          acanthosis.nigricans  acidosis  renal.tubular.acidosis  ...  \
85                           0         0                       0  ...   
119                          0         0                       0  ...   
137                          0         0                       0  ...   
143                          0         0                       0  ...   
158                          0         1                       0  ...   
...                        ...       ...                     ...  ...   
6398525                      0         0                       0  ...   
6398970                      0         0                       0  ...   
6447131                      0         0                       0  ...   
6918453                      0         0                       0  ...   
11947681                     0         0                       0  ...   

          vitamin.deficiency  drug.dependence  diverticulosis  \
85                         0                1               0   
119                        0                0               0   
137                        0                0               0   
143                        0                0               0   
158                        0                0               0   
...                      ...              ...             ...   
6398525                    0                0               0   
6398970                    0                0               0   
6447131                    0                0               0   
6918453                    0                0               0   
11947681                   0                0               0   

          prostatic.hypertrophy  allergic.reaction  dysphonia  \
85                            0                  1          0   
119                           0                  0          0   
137                           0                  0          0   
143                           0                  0          0   
158                           0                  0          0   
...                         ...                ...        ...   
6398525                       0                  0          0   
6398970                       0                  1          0   
6447131                       0                  

In [6]:
new_pauwel = pauwel.fillna(999).values
print(new_pauwel)
new_mizutani = mizutani.fillna(999).values
print(new_mizutani)

[[1 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 1 ... 0 0 0]
 [0 0 1 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
[[1 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 1 ... 0 0 0]
 [0 0 1 ... 0 0 0]
 [0 0 1 ... 0 0 0]]


In [7]:
# There are no missing values in the dataset
num_missing_pauwel = np.argwhere(new_pauwel == 999)
print(num_missing_pauwel)

num_missing_mizutani = np.argwhere(new_mizutani == 999)
print(num_missing_mizutani)

[]
[]


In [8]:
pauwel.shape

(888, 1385)

In [9]:
# check the density/sparsity of the pauwel dataset
density = float(len(np.nonzero(pauwel.to_numpy())[0]))
density /= (pauwel.shape[0]*pauwel.shape[1])
density *= 100
print('{:.2f}%'.format(density))

4.97%


In [18]:

def train_test_split(drug_se):
        train=drug_se.sample(frac=0.9,replace=False, random_state=100)
        test=drug_se.drop(train.index).sample(frac=1.0, replace=False, random_state=100)
        
        return train, test
        

In [19]:
p_train, p_test = train_test_split(pauwel)

In [20]:
p_train

abdominal cramps  abdominal distention  \
ethylenediaminetetraacetic acid                 0                     0   
cephem                                          0                     0   
fluvoxamine                                     0                     0   
perphenazine                                    0                     0   
fludrocortisone                                 0                     1   
...                                           ...                   ...   
azithromycin                                    0                     0   
dipivefrin                                      0                     0   
norepinephrine                                  0                     0   
atovaquone                                      0                     0   
nicotinic acid                                  0                     0   

                                 abdominal pain  malformations  \
ethylenediaminetetraacetic acid               0              0   
cephem                                        1              0   
fluvoxamine                                   1              0   
perphenazine                                  0              0   
fludrocortisone                               0              0   
...                                         ...            ...   
azithromycin                                  1              0   
dipivefrin                                    0              0   
norepinephrine                                0              0   
atovaquone                                    1              0   
nicotinic acid                                0              0   

                                 spontaneous abortion  missed abortion  \
ethylenediaminetetraacetic acid                     0                0   
cephem                                              0                0   
fluvoxamine                                         0                0   
perphenazine                                        0                0   
fludrocortisone                                     0                0   
...                                               ...              ...   
azithromycin                                        0                0   
dipivefrin                                          0                0   
norepinephrine                                      0                0   
atovaquone                                          0                0   
nicotinic acid                                      0                0   

                                 abscess  acanthosis nigricans  acidosis  \
ethylenediaminetetraacetic acid        0                     0         0   
cephem                                 0                     0         0   
fluvoxamine                            1                     0         0   
perphenazine                           0                     0         0   
fludrocortisone                        0                     0         0   
...                                  ...                   ...       ...   
azithromycin                           0                     0         0   
dipivefrin                             0                     0         0   
norepinephrine                         0                     0         1   
atovaquone                             0                     0         0   
nicotinic acid                         0                     1         0   

                                 renal tubular acidosis  ...  drug dependence  \
ethylenediaminetetraacetic acid                       0  ...                0   
cephem                                                0  ...                0   
fluvoxamine                                           0  ...                1   
perphenazine                                          0  ...                0   
fludrocortisone                                       0  ...                0   
...                                                

In [21]:
p_test

abdominal cramps  abdominal distention  abdominal pain  \
timolol                      0                     0               0   
benzydamine                  0                     0               0   
flurazepam                   0                     0               0   
fosinopril                   0                     1               1   
nevirapine                   0                     0               1   
...                        ...                   ...             ...   
polythiazide                 0                     0               0   
posaconazole                 0                     1               1   
Implanon                     0                     0               1   
doxycycline                  0                     1               1   
alosetron                    0                     1               0   

              malformations  spontaneous abortion  missed abortion  abscess  \
timolol                   0                     0                0        0   
benzydamine               0                     0                0        0   
flurazepam                0                     0                0        0   
fosinopril                0                     0                0        0   
nevirapine                0                     0                0        0   
...                     ...                   ...              ...      ...   
polythiazide              0                     0                0        0   
posaconazole              0                     0                0        0   
Implanon                  0                     0                0        0   
doxycycline               0                     0                0        0   
alosetron                 0                     0                0        0   

              acanthosis nigricans  acidosis  renal tubular acidosis  ...  \
timolol                          0         0                       0  ...   
benzydamine                      0         0                       0  ...   
flurazepam                       0         0                       0  ...   
fosinopril                       0         0                       0  ...   
nevirapine                       0         0                       0  ...   
...                            ...       ...                     ...  ...   
polythiazide                     0         0                       0  ...   
posaconazole                     0         0                       1  ...   
Implanon                         0         0                       0  ...   
doxycycline                      0         0                       0  ...   
alosetron                        0         0                       0  ...   

              drug dependence  diverticulosis  prostatic hypertrophy  \
timolol                     0               0                      0   
benzydamine                 0               0                      0   
flurazepam                  0               0                      0   
fosinopril                  0               0                      0   
nevirapine                  0               0                      0   
...                       ...             ...                    ...   
polythiazide                0               0                      0   
posaconazole                0               0                      0   
Implanon                    0               0                      0   
doxycycline                 0               0                      0   
alosetron                   0               0                      0   

              allergic reaction  dysphonia  eosinophilic pneumonia  \
timolol                       1          0                       0   
benzydamine                   0          0                       0   
flurazepam                    1          0                       0   
fosinopril                    0          0                       0   
nevirapine                    1          0                  